using codegencore.Models;
using codegencore.Writers.Lang;
using extgen.Bridge.Objc;
using extgen.Emitters.Utils;
using extgen.Extensions;
using extgen.Models;
using extgen.Models.Utils;
using extgen.TypeSystem;
using extgen.Utils;

namespace extgen.Emitters.AppleMobile.Objc
{
    internal enum AppleOSTargetKind { Objc, Swift }

    internal class ObjcCommonEmitter(ObjcEmitterContext ctx, IIrTypeMap cppTypeMap, IAppleBridge bridge)
    {
        // =====================================================================
        // INTERNAL BASE — {Ext}Internal.h / .mm
        //    - holds the *current* implementation
        //    - exposes Objc class entry points __EXT_NATIVE__...
        // =====================================================================
        public void EmitInternal(IrCompilation c, ObjcLayout layout) 
        {
            var platform = ctx.Settings.Platform;

            bridge.EmitWire(layout);

            FileEmitHelpers.WriteObjc(layout.CodeGenDir, $"{c.Name}Internal_{platform}.h", w => EmitInternalHeader(ctx, c, w));
            FileEmitHelpers.WriteObjc(layout.CodeGenDir, $"{c.Name}Internal_{platform}.mm", w => EmitInternalImpl(ctx, c, w));
        }

        public void EmitObjcUserShell(IrCompilation c, ObjcLayout layout)
        {
            var ext = ctx.ExtName;
            var options = ctx.Settings;
            var platform = ctx.Settings.Platform;

            FileEmitHelpers.WriteObjcIfMissing(layout.SourceDir, $"{string.Format(options.SourceFilename, ext)}.h", w => EmitUserHeader(ctx, w));
            FileEmitHelpers.WriteObjcIfMissing(layout.SourceDir, $"{string.Format(options.SourceFilename, ext)}.mm", w => EmitUserImpl(ctx, w));
        }

        // ------------- internal bridge (shared – switchable call target)

        private void EmitInternalHeader(ObjcEmitterContext ctx, IrCompilation c, ObjcWriter w)
        {
            var ext = c.Name;

            w.PragmaOnce()
                .Import("Foundation/Foundation.h", true)
                .Line();

            // Bridge-specific artifacts (ObjC enums, structs, codecs)
            bridge.EmitHeaderArtifacts(ctx, c, w);

            // Bridge-specific header extras (ObjC protocol, etc)
            bridge.EmitExtraHeaderDeclarations(ctx, c, w, cppTypeMap);

            var usesFunctions = c.HasFunctionType();
            var usesBuffers = c.HasBufferType();

            // 1. internal code gen signatures
            w.Interface($"{ext}Internal", body: body =>
            {
                var allFunctions = c.Functions.Select(f => f).Concat(c.Structs.SelectMany(s => s.Functions.Select(f => IrFunctionUtil.PatchStructMethod(s, f))));
                foreach (var fn in allFunctions)
                {
                    string methodName = $"{ctx.Runtime.NativePrefix}{fn.Name}";
                    var ps = ExportTypeUtils.ParamsFor(fn, ctx.Runtime);
                    body.MethodDecl(false, ExportTypeUtils.ReturnFor(fn).AsCppType(), methodName, [.. ps.AsObjc()]);
                }

                if (usesFunctions)
                {
                    body.MethodDecl(false, "double", $"{ctx.Runtime.NativePrefix}{ext}_invocation_handler", [new("", "char*", ctx.Runtime.RetBufferParam), new("arg1", "double", ctx.Runtime.RetBufferLengthParam)]);
                }

                if (usesBuffers)
                {
                    body.MethodDecl(false, "double", $"{ctx.Runtime.NativePrefix}{ext}_queue_buffer", [new("", "char*", ctx.Runtime.ArgBufferParam), new("arg1", "double", ctx.Runtime.ArgBufferLengthParam)]);
                }

            }).Line();
        }

        private void EmitInternalImpl(ObjcEmitterContext ctx, IrCompilation c, ObjcWriter w)
        {
            var ext = c.Name;
            var platform = ctx.Settings.Platform;

            w.Comment("AUTOGENERATED by your tool — DO NOT EDIT")
                .Import($"{ext}Internal_{platform}.h")
                .Line();

            // Bridge-specific imports (#import Swift.h + namespace, or nothing)
            bridge.EmitExtraImports(ctx, w);

            w.ClassExtension($"{ext}Internal", extInt =>
            {
                // Ivars are bridge-specific
                bridge.EmitIvars(ctx, c, extInt);

            }).Line();

            // ObjC class implementation
            w.Implementation($"{ext}Internal", impBody =>
            {
                impBody.InitMethod(initBody =>
                {
                    // Bridge-specific init (assign __impl)
                    bridge.EmitInitBody(ctx, initBody);
                });

                var allFunctions = c.Functions.Select(f => f).Concat(c.Structs.SelectMany(s => s.Functions.Select(f => IrFunctionUtil.PatchStructMethod(s, f))));
                foreach (var fn in allFunctions)
                {
                    var ps = ExportTypeUtils.ParamsFor(fn, ctx.Runtime);
                    var ret = ExportTypeUtils.ReturnFor(fn).AsCppType();

                    impBody.Method(false, ret, $"{ctx.Runtime.NativePrefix}{fn.Name}", [.. ps.AsObjc()], fnBody =>
                    {
                        bridge.EmitMethodBody(ctx, fnBody, fn);
                    })
                    .Line();
                }

                var usesFunctions = c.HasFunctionType();
                var usesBuffers = c.HasBufferType();

                if (usesFunctions)
                {
                    // invocation handler as INSTANCE method
                    impBody.Comment("Internal function used for fetching dispatched function calls to GML");
                    bridge.EmitInvocationHandlerMethod(ctx, impBody);
                }

                if (usesBuffers)
                {
                    // queue buffer as INSTANCE method
                    impBody.Comment("Internal function used for queueing buffers to native code");
                    bridge.EmitQueueBufferMethod(ctx, impBody);
                }
            });
        }

        // ------------- public user shell
        private void EmitUserHeader(ObjcEmitterContext ctx, ObjcWriter w)
        {
            var ext = ctx.ExtName;
            var platform = ctx.Settings.Platform;

            w.Import("Foundation/Foundation.h", true)
                .Import($"{platform}/{ext}Internal_{platform}.h")
                .Line();

            w.Interface(ext, $"{ext}Internal", bridge.UserShellProtocols(ctx), null)
                .Line();
        }

        private static void EmitUserImpl(ObjcEmitterContext ctx, ObjcWriter w)
        {
            var ext = ctx.ExtName;
            var platform = ctx.Settings.Platform;

            w.Import("objc/runtime.h");
            w.Import($"{ext}_{platform}.h")
                .Line();

            w.Implementation(ext, (_) => {

                _.Lines($$"""

                    + (void)load {
                        // 1) snapshot methods defined *directly* on the subclass
                        unsigned subCount = 0;
                        Method *subList = class_copyMethodList(self, &subCount);

                        // build a set of SELs the subclass already owns
                        CFMutableSetRef owned = CFSetCreateMutable(kCFAllocatorDefault, 0, NULL);
                        for (unsigned i = 0; i < subCount; ++i) {
                            SEL sel = method_getName(subList[i]);
                            CFSetAddValue(owned, sel);
                        }

                        // 2) walk the superclass’s instance methods
                        unsigned supCount = 0;
                        Method *supList = class_copyMethodList([{{ext}}Internal class], &supCount);

                        for (unsigned i = 0; i < supCount; ++i) {
                            SEL sel = method_getName(supList[i]);

                            // (optional) only copy your extension selectors
                            const char *name = sel_getName(sel);
                            if (!name || strncmp(name, "__EXT_NATIVE__", 13) != 0) continue;

                            // only add if NOT already defined on subclass
                            if (!CFSetContainsValue(owned, sel)) {
                                IMP imp = method_getImplementation(supList[i]);
                                const char *types = method_getTypeEncoding(supList[i]);
                                if (class_addMethod(self, sel, imp, types)) {
                                    // remember we added it (avoid re-adding if +load ever runs twice)
                                    CFSetAddValue(owned, sel);
                                }
                            }
                        }

                        // 3) cleanup
                        if (subList) free(subList);
                        if (supList) free(supList);
                        if (owned) CFRelease(owned);
                    }

                    """);

            });
        }

    }
}
